import type Gesture from '@huangjs888/gesture';
import { type Image, type ImageOption } from './image';
import { type RectSize } from './popup';
declare class Picture {
    _container: HTMLElement | null;
    _backdrop: HTMLElement | null;
    _rectSize: RectSize | null;
    _isClose: boolean;
    _swipeClose: boolean;
    _closeDestory: boolean;
    _originRect: RectSize | null;
    _press: (() => void) | null;
    _longPress: (() => void) | null;
    _onChange: (() => void) | null;
    _onImageEnd: ((o: boolean) => void) | null;
    _removeResize: (() => void) | null;
    _image: Image | null;
    _gesture: Gesture | null;
    _fgBehavior: number;
    constructor({ container: ele, url, hasLoading, swipeClose, closeDestory, backdropColor, originRect, press, longPress, onResize, options, }: COption);
    resetItemSize(): void;
    destory(): void;
    setSwipeClose(swipeClose?: boolean): void;
    setCloseDestory(closeDestory?: boolean): void;
    setOriginRect(originRect?: RectSize | null): void;
    open(): void;
    close(): void;
}
export type COption = {
    container?: HTMLElement | string;
    url?: string;
    backdropColor?: string;
    hasLoading?: boolean;
    originRect?: RectSize;
    swipeClose?: boolean;
    closeDestory?: boolean;
    options?: ImageOption;
    press?: () => void;
    longPress?: () => void;
    onResize?: () => void;
    onImageEnd?: (o: boolean) => void;
};
export default Picture;
